# Generated by Django 5.1.2 on 2024-11-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_table_alter_category_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
    ]
