# Generated by Django 5.1.2 on 2024-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='books/'),
        ),
    ]
